<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoviesApp.DataAccess\MoviesApp.DataAccess.csproj" />
    <ProjectReference Include="..\MoviesApp.Services\MoviesApp.Services.csproj" />
  </ItemGroup>

</Project>
