// <auto-generated />
using System;
using ASP.NET.Core.MVC.Database.Class09.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET.Core.MVC.Database.Class09.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    partial class DemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET.Core.MVC.Database.Class09.Models.Domains.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActiveCourse")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfClasses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActiveCourse = false,
                            Name = "C# basic",
                            NumberOfClasses = 40
                        },
                        new
                        {
                            Id = 2,
                            IsActiveCourse = false,
                            Name = "C# Advanced",
                            NumberOfClasses = 60
                        },
                        new
                        {
                            Id = 3,
                            IsActiveCourse = false,
                            Name = "Database development and design",
                            NumberOfClasses = 28
                        },
                        new
                        {
                            Id = 4,
                            IsActiveCourse = false,
                            Name = "ASP.NET Mvc",
                            NumberOfClasses = 40
                        });
                });

            modelBuilder.Entity("ASP.NET.Core.MVC.Database.Class09.Models.Domains.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveCourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveCourseId = 4,
                            DateOfBirth = new DateTime(1999, 7, 13, 19, 59, 59, 840, DateTimeKind.Local).AddTicks(2976),
                            FirstName = "Bob",
                            LastName = "Bobski"
                        },
                        new
                        {
                            Id = 2,
                            ActiveCourseId = 4,
                            DateOfBirth = new DateTime(1989, 7, 13, 19, 59, 59, 840, DateTimeKind.Local).AddTicks(3023),
                            FirstName = "Jill",
                            LastName = "Jilski"
                        },
                        new
                        {
                            Id = 3,
                            ActiveCourseId = 4,
                            DateOfBirth = new DateTime(1981, 7, 13, 19, 59, 59, 840, DateTimeKind.Local).AddTicks(3025),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 4,
                            ActiveCourseId = 4,
                            DateOfBirth = new DateTime(2009, 7, 13, 19, 59, 59, 840, DateTimeKind.Local).AddTicks(3028),
                            FirstName = "Jane",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("ASP.NET.Core.MVC.Database.Class09.Models.Domains.Student", b =>
                {
                    b.HasOne("ASP.NET.Core.MVC.Database.Class09.Models.Domains.Course", "ActiveCourse")
                        .WithMany()
                        .HasForeignKey("ActiveCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
