<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibraryApi.Domain\LibraryApi.Domain.csproj" />
    <ProjectReference Include="..\LibraryApi.Dtos\LibraryApi.Dtos.csproj" />
    <ProjectReference Include="..\LibraryApi.Services\LibraryApi.Services.csproj" />
    <ProjectReference Include="..\LibraryApi.DataAccess\LibraryApi.DataAccess.csproj" />
  </ItemGroup>

</Project>
